version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - app-network

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler_container
    volumes:
      - type: bind
        source: ./datalake
        target: /app/datalake
    networks:
      - app-network

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: indexer_container
    volumes:
      - type: bind
        source: ./datalake
        target: /app/datalake
      - type: bind
        source: ./datamart
        target: /app/datamart
    environment:
      - DATATYPE=MongoDB
    networks:
      - app-network
    depends_on:
      - mongodb

  query_engine:
    build:
      context: ./query_engine
      dockerfile: Dockerfile
    container_name: query_engine_container
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./datalake
        target: /app/datalake
      - type: bind
        source: ./datamart
        target: /app/datamart
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui_container
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://query_engine:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge