version: '3.7'

services:
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler_container
    volumes:
      - ./datalake_document_repository:/app/datalake_document_repository  # Zapis dokumentów
    networks:
      - app-network

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: indexer_container
    volumes:
      - ./datalake_document_repository:/app/datalake_document_repository  # Odczyt dokumentów
      - ./datalake_inverted_index:/app/datalake_inverted_index  # Zapis indeksów
    networks:
      - app-network

  queryengine:
    build:
      context: ./queryengine
      dockerfile: Dockerfile
    container_name: queryengine_container
    ports:
      - "8080:8080"
    volumes:
      - ./datalake_document_repository:/app/datalake_document_repository  # Odczyt dokumentów
      - ./datalake_inverted_index:/app/datalake_inverted_index  # Odczyt indeksów
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui_container
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://queryengine:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
